# Generated by Django 3.2.5 on 2021-07-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creditform',
            new_name='credit',
        ),
    ]
