# Generated by Django 3.2.5 on 2021-07-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_creditform_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credit',
            new_name='creditform',
        ),
    ]
